### ISSUE TITLE
[post] 게시글 전체 및 상세 조회 기능 구현

### ISSUE THREAD

**Issue by yeonwoo1125** [ywoo-srin-minj/spring_study#41]

**Comment by m04j00** [comment]
### 이슈 #41, #42 묶음
오늘 구현할 기능은 전체 조회, 상세 조회 기능인데 DTO를 공통으로 사용하여 두 개의 이슈를 한 개로 합쳤습니다.

## 전체 조회 참고
### 도메인 
```[GET] /posts-name?userpk=```
- ```userpk```는 경로 변수로 받습니다. 
- ```@RequestParam``` 어노테이션 사용
  - 해당 변수는 상황에 따라 받을 수도 있고 안 받을 수도 있습니다. **참고 : required**

### NPE(Null Pointer Exception) 발생할 경우
user PK을 long 타입이라 명시할 경우 날 수 있는 오류입니다.
long 타입은 null값을 허용하지 못하니 Long타입을 사용해야 정상적으로 돌아갈 수 있습니다.

### 짚고 넘어가기 : user PK에 대한 예외처리?
게시글 전체 조회 API에서는 userPk가 존재하는지 체크하지 않습니다.
내가 어떤 웹사이트에서 무엇을 검색했는데 그 값이 없다고 오류를 던지는 사이트를 본 적이 있는지 생각해봅니다.
목록 리스트는 있는 대로 보여주고 없으면 없는 리스트를 반환하세요.
리스트가 비었을 때의 처리는 해당 API를 사용하는 클라이언트가 처리할 부분입니다.

### QueryDSL 사용하기
querydsl과 관련된 파일을 또 생성하기는 귀찮으니 User에 있는 querydsl에서 작업하도록 하겠습니다. 
그럴 경우 서비스에서는 userRepository에서 메소드를 찾으면 됩니다.
- 메소드 반환 타입은 Entity가 아닌 DTO여야 합니다.  **참고 - https://doing7.tistory.com/129**
- user PK를 매개변수로 받는데 이 값이 null일 경우 무시하여 조회할 수 있습니다. **참고 - https://jojoldu.tistory.com/394**
- 쿼리문을 작성하면서 최신순으로 정렬해보세요.

## 게시글 상세 조회 참고
### 도메인 변경
```[POST] /posts-name/details/{id}```

게시글 생성 API에서 post 메소드를 사용해버렸습니다. 그래서 해당 API 도메인을 수정하였습니다.
